default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: friend_app_a_development

test:
  <<: *default
  database: friend_app_a_test

production:
  <<: *default
  database: friend_app_a_production
  username: friend_app_a
  password: <%= ENV['FRIEND_APP_A_DATABASE_PASSWORD'] %>
